name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construction de l'image Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/image-backend:latest ./backend

      - name: Push de l'image sur Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/image-backend:latest
